version: "3.9"
services:
   web:
     build: .
     network_mode: "host" 
     volumes:
       - .:/home/node/app
     ports:
       - "3000:3000"

   jupyter:
     build: 
       context: .
       dockerfile: ./webhook/Dockerfile
     environment:
       - JUPYTER_TOKEN=migi
     network_mode: "host" 
     volumes:
       - ./tensor_flow/:/home/jovyan/work
       - ./webhook/:/home/jovyan/webhook
     ports:
       - "8888:8888"
